version: '3.8'

services:
  db:
    platform: linux/amd64
    image: mysql:5.5
    # image: mysql:8.0.35 # mysql更新時はここを書き換える
    container_name: wp-mysql55-temp
    ports:
      - "33060:3306"
    volumes:
      - db_data_temp:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wp_db_temp
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wp_password

  wordpress:
    # wordpressイメージはこちらの中
    build: ./wordpress
    container_name: wp-app-temp
    ports:
      - "8080:80"
    volumes:
      - ./html:/var/www/html
      - ./php.ini:/usr/local/etc/php/conf.d/uploads.ini
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: wp_password
      WORDPRESS_DB_NAME: wp_db_temp


volumes:
  db_data_temp: